config/routes.rb
Rails.application.routes.draw do
  
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
  
  devise_for :users
  
  resources :chatrooms
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'chatrooms#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :users, through: :messages
  validates :topic, presence: true, uniqueness: true, case_sensitive: false
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
  
  after_create_commit { MessageBroadcastJob.perform_later self }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages
  has_many :chatrooms, through: :messages
  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception, prepend: true
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password) }
    end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
    
  before_action :authenticate_user!, :only => [:show]
  
  def index
    @chatrooms = Chatroom.all
    @chatroom  = Chatroom.new
  end
  
  def show
    @chatroom = Chatroom.find_by(id: params[:id])
    @users    = @chatroom.messages.map(&:user)
    @message  = Message.new
  end
  
  def create
    @chatroom = Chatroom.new(chatroom_params)
    if @chatroom.save
      respond_to do |format|
        format.html { redirect_to @chatroom }
        format.js
      end
    else
      respond_to do |format|
        flash[:notice] = {error: ["a chatroom with this topic already exists"]}
        format.html { redirect_to new_chatroom_path }
        format.js { render template: 'chatrooms/chatroom_error.js.erb'} 
      end
    end
  end
  
  private

    def chatroom_params
      params.require(:chatroom).permit(:topic)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/views/chatrooms/_chatroom.html.erb
<div><p><%= link_to chatroom.topic, chatroom_path(chatroom) %></p></li>

app/views/chatrooms/_chatroom_form.html.erb
<div class="chatroom-form">
  <%= form_for chatroom, remote: true do |f| %>
    <div class="input-group">
      <span class="input-group-addon">topic:</span>
      <%= f.text_field :topic, class: "form-control"%>
    </div>
    <%= f.submit class: "btn btn-primary", id: "create-chatroom" %>
  <% end %>
</div>

app/views/chatrooms/index.html.erb
<div class="row col-md-8 col-md-offset-2" id="chatroom-title">
  <h1>Chatrooms</h1>
</div>

<div class="row col-md-8 col-md-offset-2" id="chatrooms">
  <%= render partial: 'chatroom_form', locals: {chatroom: @chatroom} %>
  
  <div id="chatroom-errors"></div>
  
  <div id="chatrooms"> 
    <% if @chatrooms.any? %>
        <%= render @chatrooms%>
    <%else %>
      <p>Be the first one to make a chatroom!</p>
    <% end %>
  </div>
</div>

app/views/chatrooms/show.html.erb
<div id="chat-window" class="container">
  
  <div class="row">
    <div class="col-md-12">
      <h1><%= @chatroom.topic %></h1>
    </div>
  </div>
  
  <div class="row">
    <div id="messages" class="col-md-12">
      <%= render partial: 'messages/message', collection: @chatroom.messages  if @chatroom.messages.any? %>
    </div>
  </div>
  
  <form>
    <div class="form-group">
      <input type="text" class="form-control" id="message-input" placeholder="Say something" data-behavior="room_speaker" chatroom-id="<%= @chatroom.id %>">
    </div>
  </form>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chipchat</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= action_cable_meta_tag %>
  </head>

  <body>
    <%= render 'devise/menu/header' %>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<p>
    <%=message.user.username + ' >> ' + message.content%>
    <span class="pull-right text-right"><%= message.created_at.strftime("%a %I:%M %p") %></span>
</p>